import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:logmate_visual_preview/home_candidate_12_visual.dart';
const _sans='PreviewSans';
Future<void> _loadFonts()async{final sets=[['/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf','/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'],['/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf','/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf']];final sans=sets.firstWhere((s)=>s.every((p)=>File(p).existsSync()),orElse:()=>throw StateError('No sans'));final sl=FontLoader(_sans);for(final p in sans){final b=await File(p).readAsBytes();sl.addFont(Future<ByteData>.value(ByteData.sublistView(Uint8List.fromList(b))));}await sl.load();final mp=['/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf','/usr/share/fonts/truetype/liberation2/LiberationMono-Regular.ttf'].firstWhere((p)=>File(p).existsSync());final mb=await File(mp).readAsBytes();await(FontLoader('monospace')..addFont(Future<ByteData>.value(ByteData.sublistView(Uint8List.fromList(mb))))).load();final root=Platform.environment['FLUTTER_ROOT'];if(root!=null){final f=File('$root/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf');if(f.existsSync()){final b=await f.readAsBytes();await(FontLoader('MaterialIcons')..addFont(Future<ByteData>.value(ByteData.sublistView(Uint8List.fromList(b))))).load();}}}
Future<void> shot(WidgetTester t,Brightness b,String f)async{await t.binding.setSurfaceSize(const Size(390,844));addTearDown(()=>t.binding.setSurfaceSize(null));await t.pumpWidget(MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(brightness:Brightness.light,fontFamily:_sans),darkTheme:ThemeData(brightness:Brightness.dark,fontFamily:_sans),themeMode:b==Brightness.dark?ThemeMode.dark:ThemeMode.light,home:const HomeCandidate12Visual()));await t.pumpAndSettle();expect(t.takeException(),isNull);await expectLater(find.byType(Scaffold).first,matchesGoldenFile('goldens/$f'));}
void main(){setUpAll(_loadFonts);testWidgets('Candidate 12 light 390x844',(t)=>shot(t,Brightness.light,'candidate12_light_390x844.png'));testWidgets('Candidate 12 dark 390x844',(t)=>shot(t,Brightness.dark,'candidate12_dark_390x844.png'));}
