name: logmate_visual_preview
description: Design-only LogMate visual preview. Not production app code.
publish_to: 'none'

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: C16Roboto
      fonts:
        - asset: candidate16/fonts/Roboto.ttf
