import 'package:flutter/material.dart';
import 'primitives.dart';

class HomeCandidate11Visual extends StatefulWidget { const HomeCandidate11Visual({super.key}); @override State<HomeCandidate11Visual> createState()=>_S(); }
class _S extends State<HomeCandidate11Visual>{ String period='7 days'; @override Widget build(BuildContext context){
final dark=Theme.of(context).brightness==Brightness.dark; final bg=dark?const Color(0xFF11161B):const Color(0xFFF7F8F5); final ink=dark?const Color(0xFFE9EEF2):const Color(0xFF17212A); final muted=dark?const Color(0xFF9AA8B2):const Color(0xFF64717A); final rule=dark?const Color(0xFF33414A):const Color(0xFFCBD2D5); final accent=dark?const Color(0xFF8FD3E8):const Color(0xFF176A82);
TextStyle t(double s,{FontWeight w=FontWeight.w500,Color? c,double ls=0})=>TextStyle(fontSize:s,height:1.12,fontWeight:w,color:c??ink,letterSpacing:ls);
Widget section(String label,{String? action})=>SizedBox(height:40,child:Row(children:[Container(width:3,height:16,color:accent),const SizedBox(width:9),Expanded(child:Text(label.toUpperCase(),style:t(12,w:FontWeight.w800,ls:.9))),if(action!=null)Text(action,style:t(10.5,w:FontWeight.w600,c:muted))]));
Widget datum(String label,String value)=>Expanded(child:Padding(padding:const EdgeInsets.symmetric(vertical:10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label.toUpperCase(),style:t(9.5,w:FontWeight.w700,c:muted,ls:.5)),const SizedBox(height:5),Text(value,style:t(18,w:FontWeight.w600))])));
Widget flight(String date,String flight,String route,String block)=>SizedBox(height:37,child:Row(children:[SizedBox(width:52,child:Text(date,style:t(11,c:muted))),SizedBox(width:72,child:Text(flight,style:t(12,w:FontWeight.w600))),Expanded(child:Text(route,style:t(12))),SizedBox(width:45,child:Text(block,textAlign:TextAlign.end,style:t(12,w:FontWeight.w600))) ]));
Widget action(IconData icon,String label)=>Expanded(child:SizedBox(height:44,child:InkWell(onTap:(){},child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:16,color:accent),const SizedBox(width:7),Text(label,style:t(12.5,w:FontWeight.w700))]))));
Widget stats(List<(String,String)> xs)=>Container(decoration:BoxDecoration(border:Border(top:BorderSide(color:rule),bottom:BorderSide(color:rule))),child:Row(children:[for(var i=0;i<xs.length;i++)...[Expanded(child:Padding(padding:const EdgeInsets.symmetric(vertical:9),child:Column(children:[Text(xs[i].$1.toUpperCase(),style:t(9.5,w:FontWeight.w700,c:muted,ls:.4)),const SizedBox(height:5),Text(xs[i].$2,style:t(13,w:FontWeight.w700))]))),if(i<xs.length-1)Container(width:1,height:27,color:rule)]]));
return Theme(data:ThemeData(brightness:dark?Brightness.dark:Brightness.light,useMaterial3:true,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:accent,brightness:dark?Brightness.dark:Brightness.light,surface:bg)),child:PreviewPage(padding:const EdgeInsets.fromLTRB(20,8,20,24),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[SizedBox(height:44,child:Stack(alignment:Alignment.centerLeft,children:[Text('LOGMATE',style:t(16,w:FontWeight.w900,ls:1.5)),Align(alignment:Alignment.centerRight,child:IconButton(onPressed:(){},tooltip:'Settings',icon:Icon(Icons.tune_rounded,size:19,color:muted)))])),Container(decoration:BoxDecoration(border:Border(top:BorderSide(color:rule),bottom:BorderSide(color:rule))),child:Row(children:[action(Icons.add_rounded,'Add Flight'),Container(width:1,height:20,color:rule),action(Icons.menu_book_outlined,'View Logbook')])),const SizedBox(height:4),const UnderlineSearch(hint:'Search logbook'),const SizedBox(height:10),section('Current Period',action:'‹   09/2026   ›'),Container(decoration:BoxDecoration(border:Border(top:BorderSide(color:rule),bottom:BorderSide(color:rule))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Padding(padding:const EdgeInsets.only(top:8),child:Text('BLOCK TIME',style:t(9.5,w:FontWeight.w800,c:accent,ls:.8))),Row(children:[datum('This month','42+15'),Container(width:1,height:45,color:rule),datum('This year','318+40')])])),const SizedBox(height:12),section('Recent Flights',action:'VIEW ALL ›'),SizedBox(height:22,child:Row(children:[SizedBox(width:52,child:Text('DATE',style:t(9,c:muted))),SizedBox(width:72,child:Text('FLIGHT',style:t(9,c:muted))),Expanded(child:Text('ROUTE',style:t(9,c:muted))),SizedBox(width:45,child:Text('BLOCK',textAlign:TextAlign.end,style:t(9,c:muted)))])),Divider(height:1,color:rule),flight('09.02','7C 132','GMP  →  CJU','1+12'),Divider(height:1,color:rule),flight('08.31','7C 1123','CJU  →  GMP','1+08'),Divider(height:1,color:rule),flight('08.29','KE 28','GMP  →  CJU','1+10'),Divider(height:1,color:rule),const SizedBox(height:12),section('Activity',action:'DETAILS ›'),Row(children:[for(final p in ['7 days','28 days','90 days','Custom'])Expanded(child:InkWell(onTap:()=>setState(()=>period=p),child:Container(height:42,decoration:BoxDecoration(border:Border(bottom:BorderSide(width:period==p?3:1,color:period==p?accent:rule))),child:Center(child:Text(p,style:t(10,w:period==p?FontWeight.w800:FontWeight.w500,c:period==p?ink:muted))))))]),const SizedBox(height:7),stats([('Legs','4'),('Block','6+48'),('TO / LD','3 / 3')]),const SizedBox(height:12),section('Totals',action:'DETAILS ›'),stats([('Total','1,284+35'),('B737','842+10'),('SIC','1,163+55')])]))); }}